// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHlOQ5VQHbDNFH6rhAtVpxLC-MvARU48',
    appId: '1:553381381690:web:9f4202b3218fb00c831703',
    messagingSenderId: '553381381690',
    projectId: 'firebase-todo-sync',
    authDomain: 'fir-todo-sync.firebaseapp.com',
    storageBucket: 'firebase-todo-sync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTzZ5539BMa043cIoV6bpcBwM9-Pw9T8',
    appId: '1:553381381690:android:245f0b8eef959397831703',
    messagingSenderId: '553381381690',
    projectId: 'firebase-todo-sync',
    storageBucket: 'firebase-todo-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBulmZnJD_Vepkmuno00VNcQZyspf2gS3E',
    appId: '1:553381381690:ios:488726c19e13b9a0831703',
    messagingSenderId: '553381381690',
    projectId: 'firebase-todo-sync',
    storageBucket: 'firebase-todo-sync.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBulmZnJD_Vepkmuno00VNcQZyspf2gS3E',
    appId: '1:553381381690:ios:488726c19e13b9a0831703',
    messagingSenderId: '553381381690',
    projectId: 'firebase-todo-sync',
    storageBucket: 'firebase-todo-sync.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRHlOQ5VQHbDNFH6rhAtVpxLC-MvARU48',
    appId: '1:553381381690:web:8f66383158e5ef22831703',
    messagingSenderId: '553381381690',
    projectId: 'firebase-todo-sync',
    authDomain: 'fir-todo-sync.firebaseapp.com',
    storageBucket: 'firebase-todo-sync.firebasestorage.app',
  );
}
